server.address=127.0.0.1
server.port=${SERVER_PORT:8080}

vault.addr=${VAULT_ADDR}
vault.namespace=${VAULT_NAMESPACE:}
vault.role=${VAULT_ROLE}
vault.mount-point=${MOUNT_POINT:secret}
vault.secret-path=${SECRET_PATH:config}
